name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: write

jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build PDF
        uses: dita-ot/dita-ot-action@4.4
        with:
          transtype: pdf
          input: dita/document.ditamap
          output-path: out/pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: dita-pdf
          path: out/pdf

      - name: Build HTML (Bootstrap)
        uses: dita-ot/dita-ot-action@4.4
        with:
          plugins: https://github.com/jason-fox/fox.jason.extend.css/archive/master.zip https://github.com/dita-bootstrap/dita-bootstrap/archive/refs/heads/master.zip
          build: |
            dita \
              --input=/github/workspace/dita/document.ditamap \
              --format=html5-bootstrap \
              --output=/github/workspace/out/html5 \
              --args.hdr=/github/workspace/.github/dita-ot/header.xml \
              --args.ftr=/github/workspace/.github/dita-ot/footer.xml \
              --args.css=theme.css \
              --args.cssroot=/github/workspace/.github/dita-ot \
              --args.copycss=yes

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out/html5
          publish_branch: gh-pages

      - name: Build Markdown
        uses: dita-ot/dita-ot-action@4.4
        with:
          transtype: markdown
          input: dita/document.ditamap
          output-path: out/markdown

      - name: Upload Markdown artifact
        uses: actions/upload-artifact@v4
        with:
          name: dita-markdown
          path: out/markdown
